### ISSUE TITLE
`inputs_for/2` (BadFunctionError) expected a function, got: []

### ISSUE THREAD

**Issue by jdav-dev** [phoenixframework/phoenix_html_helpers#2]
[inputs_for/2](https://github.com/phoenixframework/phoenix_html_helpers/blob/v1.0.1/lib/phoenix_html_helpers/form.ex#L266-L268) passes an empty list to the anonymous function argument of [inputs_for/3](https://github.com/phoenixframework/phoenix_html_helpers/blob/v1.0.1/lib/phoenix_html_helpers/form.ex#L299-L300), resulting in a `BadFunctionError`.  It looks like the [previous inputs_for/3 from Phoenix.HTML](https://github.com/phoenixframework/phoenix_html/blob/v3.3.4/lib/phoenix_html/form.ex#L631-L645) handled the list argument, but was deprecated and not carried over.

I'm happy to submit a PR for this, but I'm not sure how you'll want it fixed.

**Comment by josevalim** [comment]
Please do send a PR! It should work as it worked in Phoenix.HTML.
